theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  search:
    active: true
  logo:
    header: "/assets/images/logo_header.svg"
    footer: "/assets/images/logo_footer.svg"
  breadcrumb:
    position: after-hero
  menu:
    dropdown:
      linkToLevel1: true
